### ISSUE TITLE
create screenshot for example-sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/example-sim#10]
Over in https://github.com/phetsims/utterance-queue/issues/10, we created a published README.md file for example-sim.  But it currently does not have a screenshot, which the README.md links to.

@KatieWoe could you please create assets/example-sim-screenshot.png?  The default startup state of the sim would be fine.

**Comment by KatieWoe** [comment]
Done

**Comment by pixelzoom** [comment]
Tested at https://github.com/phetsims/example-sim/.  Looks great.  Thanks @KatieWoe!
