### ISSUE TITLE
branch: typescript

### ISSUE THREAD

**Issue by samreid** [phetsims/example-sim#12]
For https://github.com/phetsims/tasks/issues/987

**Comment by zepumph** [comment]
Can this be deleted and issue closed?

**Comment by samreid** [comment]
If we one day want example-sim to be TypeScript, this branch could save us 20-30 minutes? We last wanted example sim to be JS because of how it is used in programming tasks (like for hiring), etc. but maybe it should be TypeScript now.  So maybe keep the branch until we discuss it?  Self-unassigning.

**Comment by pixelzoom** [comment]
@samreid said:
> If we one day want example-sim to be TypeScript, this branch could save us 20-30 minutes? ...

simula-rasa is fully TypeScript, and this branch was not used.   @samreid can this branch now be deleted?  If so, please delerte it and close this issue.

**Comment by samreid** [comment]
branch "typescript" deleted, closing.
