### ISSUE TITLE
branch: additionalDevTasks

### ISSUE THREAD

**Issue by chrisklus** [phetsims/example-sim#14]
This is a branch for @solaolateju to commit changes to for additional tasks to practice on example-sim. Creating a branch for this will allow him to keep track of his progress and add version control to his changes, which he's been working without so far. It will be deleted once he is done working in example-sim.

**Comment by pixelzoom** [comment]
@solaolateju @chrisklus This branch is > 2 years old, and I see no commits by @solaolateju.  Does this branch still serve a purpose, or can we delete it?

**Comment by solaolateju** [comment]
Please delete @pixelzoom. I am no longer working on the tasks.

**Comment by pixelzoom** [comment]
OK, thanks @solaolateju.

**Comment by pixelzoom** [comment]
This branch has been deleted. Closing.
