### ISSUE TITLE
Ubuntu 14.04 Script Error

### ISSUE THREAD

**Issue by dawsonbotsford** [phetsims/example-sim#2]
I am looking to work on the example as a developer application, but I getting several script errors while running the example with "python -m SimpleHTTPServer". I downloaded each and every one of the git repos detailed [here](https://github.com/phetsims/example-sim), but after viewing the URL in my browser I am getting the following errors:

    Uncaught Error: Script error for: SCENERY/Util/Color
    Uncaught Error: Script error for: PHET_CORE/Platform
    Uncaught Error: Script error for: SCENERY/display/webgl/colorTriangleBufferData

As a quick misspell check I changed ```SCENERY/util``` to ```SCENERY/Util```, but this simply caused more bugs.

Screenshot of the browser error (attempted in both Chrome and Firefox):
![screenshot](http://i.imgur.com/Tv2Iizg.png)

System data:

    $ cat /proc/version
    Linux version 3.13.0-45-generic (buildd@phianna) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.1 LTS
    Release:        14.04
    Codename:       trusty

    $ uname -a
    Linux dawson-Alienware-17 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Has this code been used before on Ubuntu 14.04?

Thank you for your time

**Comment by samreid** [comment]
Hi @dawsonbotsford, thanks for the problem report.  None of our development staff is using Ubuntu for development at the moment, and it appears that both Windows and OSX is case insensitive:

http://apple.stackexchange.com/questions/22297/is-bash-in-osx-case-insensitive
> HFS+ (the Mac filesystem) is usually configured to be case insensitive but case preserving. This means that the file system will consider foo and FoO to be the same, but when you create a new file it will remember which letters where capitalized and which were not.

All of the issues identified above look like case sensitivity issues.  I'll work to commit fixes for them shortly, but since I don't have a case sensitive system to test on it will be difficult for me to iterate and find more of these problems (if they are masking more issues).

**Comment by samreid** [comment]
I have fixed the aforementioned casing problems in the above 2 commits.  @dawsonbotsford can you pull the changes to joist and scenery and check to see if this was masking other downstream casing issues?

**Comment by dawsonbotsford** [comment]
@samreid, those changes work. Assuming the following picture is the full vis you have made the entire software Linux compatable in a matter of moments! Thanks
![image](http://i.imgur.com/yf5fKhS.png)

**Comment by samreid** [comment]
That looks perfect, thanks for testing!  Closing.
