### ISSUE TITLE
Bring code up to current standards

### ISSUE THREAD

**Issue by samreid** [phetsims/example-sim#6]
We use example-sim as a reference in test tasks, and it should be brought up to our new level of standards as other sims according to the https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md

Issues in particular that need to be addressed:

1. We need to add visibility annotations on property assignment like `@public`, `@private`, etc.
2. Each property should be documented.
3. Better JSdoc for functions

For example, Bar Magnet's `size` property should get a comment like:

```js
    // @public {Dimension2} - the size of the bar magnet in model cooordinates 
    this.size = size;
```

And BarMagnet's reset function should get JSDoc like:

```js
    /**
     * Restores the initial state of the BarMagnet. This method is called when the simulation "Reset All" button is 
     * pressed.  Note that the BarMagnet.size size is constant and does not need to be reset.
     * @public
     */
    reset: function() {
      this.locationProperty.reset();
      this.orientationProperty.reset();
    }
```

**Comment by phet-steele** [comment]
@samreid I took a stab at this in the above commits, please review. If there is more to do, don't tell me what to change. Instead just say, "You're missing something" so I can attempt to find it myself first 😄.

Also please ignore the changes to `package.json` in 054565d8725429740230f41041f9eb3c1fc946cf (the first commit). That was a mistake that was reverted.

**Comment by samreid** [comment]
Looks great @phet-steele, some minor recommendations:

- [ ] You said "This element always exists and does not need to be disposed." in a few spots, but it would be more accurate to say "This element always exists and does not need to be unlinked."
- [ ] Please add yourself as `@author` on the files you changed.
- [ ] Can you elaborate on the top-level JSDoc for ControlPanel.js?
- [ ]  `* Control panel constructor.` is redundant and should be removed (also the blank line after it)

**Comment by phet-steele** [comment]
I hardly feel like I should be the author in any of these, but I especially don't think I should be in `ExampleScreen.js`. I added myself as author to all but that file.

@samreid recommendations have been done in the above commits. Please review and close!

**Comment by samreid** [comment]
Excellent work, thanks!  Closing.
