### ISSUE TITLE
GET /favicon.ico" Error (404): "Not found

### ISSUE THREAD

**Issue by ajaykant00** [phetsims/example-sim#8]
ajay@ajay MINGW64 ~/phetsims
$ http-server
Starting up http-server, serving ./
Available on:
  http://10.9.1.143:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /example-sim/build/example_sim.html" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /example-sim/build/example_sim.html" Error (404): "Not found"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" Error (404): "Not found"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" Error (404): "Not found"

**Comment by ajaykant00** [comment]
I am trying to open the URL http://localhost:8080/example-sim/build/example_sim.html but in git bash the above error given.

**Comment by ajaykant00** [comment]
ajay@ajay MINGW64 ~/phetsims
$ http-server
Starting up http-server, serving ./
Available on:
http://10.9.1.143:8080
http://127.0.0.1:8080
Hit CTRL-C to stop the server
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /example-sim/build/example_sim.html" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /example-sim/build/example_sim.html" Error (404): "Not found"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" Error (404): "Not found"
[Fri Jun 22 2018 11:08:11 GMT+0530 (India Standard Time)] "GET /favicon.ico" Error (404): "Not found"

**Comment by pixelzoom** [comment]
Sorry for the delayed reply!

`"GET /favicon.ico" Error (404): "Not found"` is not specific to PhET sims.  It's a warning that the "Favorites Icon" does not exist.  More general information at http://www.webweaver.nu/html-tips/favicon.shtml and https://www.xspdf.com/resolution/56546304.html.  

This is not something that PhET intended to (or needs to) address, so closing this issue.

**Comment by jdconcetto** [comment]
<link rel="shortcut icon" href="#" />
You can add this line, that error will be disappeared.
