### ISSUE TITLE
branch: accessibleScreenView

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/example-sim#9]
Contains an example usage of AccessibleScreenView to facilitate discussion in https://github.com/phetsims/scenery-phet/issues/381. Once decisions have been made in that issue this branch should be deleted.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/scenery-phet/issues/381 is closed, so presumably "decisions have been made".

@jessegreenberg can this branch be deleted?

**Comment by jessegreenberg** [comment]
This branch was deleted in https://github.com/phetsims/example-sim/issues/17.
